"""Sensible default values referenced across the codebase."""

# Agent loop limits
MAX_SANDBOX_RETRIES = 3  # Re-prompt attempts when validation fails
MAX_CONSECUTIVE_CRASHES = 5  # Hard stop after N consecutive crashes

# State filenames
AUTOTRAIN_DIR = ".autotrain"
STATE_DB_NAME = "state.db"
PID_FILE = "daemon.pid"


def create_default_config() -> str:
    """Return a default autotrain.yaml template as a string.

    Used by the dashboard /defaults endpoint and the 'Save Config' UI.
    """
    return """# AutoTrain Configuration
# Generated by AutoTrain Dashboard

repo_path: /path/to/your/training/repo

metric:
  name: val_loss        # Metric to optimize
  target: 0.1           # Target value
  direction: minimize   # "minimize" or "maximize"

agent:
  provider: openai      # LLM provider
  model: gpt-4o         # Model name
  max_retries: 3        # Max retries on API failure
  hard_timeout_seconds: 120
  temperature: 0.7
  stagnation_threshold: 3

budget:
  max_iterations: 20           # Max agent iterations
  max_api_cost_usd: 10.0       # Max total LLM API cost
  experiment_timeout_seconds: 1800  # Max time per training run
  time_seconds: 14400          # Max total budget time

execution:
  mode: local           # "local" or "ssh"
  train_command: python train.py
  # SSH mode (uncomment if using remote GPU):
  # mode: ssh
  # ssh_host: gpu-server.local
  # ssh_remote_dir: /home/user/training
  # ssh_port: 22
  # ssh_key: ~/.ssh/id_rsa
  checkpoint_patterns:
    - "*.pt"
    - "*.pth"
    - "checkpoint_*"

sandbox:
  writable_files:
    - train.py
  max_file_size_bytes: 100000
  max_changes_per_iteration: 5
  forbidden_patterns:
    - "subprocess"
    - "os\\.system"
    - "eval\\("
    - "exec\\("

notify:
  terminal: true        # Print notifications to terminal
  webhook_url: ""       # Optional Slack/Discord webhook

watchdog:
  interval_seconds: 2.0
  gpu_temp_limit: 85
  gpu_mem_limit_pct: 95
  inactivity_timeout: 600
"""

